### ISSUE TITLE
TypeError: string is not a function

### ISSUE THREAD

**Issue by rngadam** [rhyolight/sprinter.js#35]
sprinter 1.0.0 (from npm)

while trying to listIssues:

```
/Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/sprinter.js:151
                        return callback(err);
                               ^
TypeError: string is not a function
    at resultCacher (/Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/sprinter.js:151:32)
    at resultHandler (/Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/sprinter.js:323:13)
    at /Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/sprinter.js:204:9
    at /Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/node_modules/async/lib/async.js:238:13
    at done (/Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/node_modules/async/lib/async.js:120:15)
    at /Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/node_modules/async/lib/async.js:25:16
    at /Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/node_modules/async/lib/async.js:235:17
    at /Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/node_modules/async/lib/async.js:525:34
    at /Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/sprinter.js:310:24
    at /Users/rngadam/thecarevoice/src/eng-dashboard/node_modules/sprinter/node_modules/async/lib/async.js:542:17
```

The code in question has a var callback and I don't see where the callback actually gets set:

```
Sprinter.prototype._setupCaching = function() {
    var cacheDuration = this._cacheDuration
      , me = this;
    _.each(originalPrototypeFunctions, function(fn, name) {
        if (name.indexOf('get') == 0) {
            // console.log('wrapping %s', name);
            me[name] = function() {

                // Default cache key is function name.
                var cacheKey = name
                  , callback
                  , newArguments = [];

                function resultCacher(err, result) {
                    // Don't cache on error.
                    if (err) {
                        return callback(err);
                    }
                    // Don't cache if duration is 0.
                    if (me._cacheDuration) {
                        // console.log('caching response for %s', cacheKey);
                        me._CACHE[cacheKey] = {
                            time: new Date().getTime()
                          , value: result
                        };
                    }
                    callback(err, result);
                }
```

**Comment by rhyolight** [comment]
@rngadam ping
